#!/usr/bin/python3
# SPDX-License-Identifier: Apache-2.0

import enarxbot

TO_RENAME = {
    'amd sev': 'sev'
}

github = enarxbot.connect()
org = github.get_organization('enarx')
enarx = github.get_repo("enarx/enarx")

ORGANIZATION_LABELS = enarxbot.ORGANIZATION_LABELS
organization_label_names = {l for l in ORGANIZATION_LABELS.keys()}

for repo in org.get_repos():
    repo_labels = {l.name: l for l in repo.get_labels()}

    # Rename labels that need to be renamed.
    for name in TO_RENAME.items():
        if name[1] not in organization_label_names:
            print(f"WARNING: {name[1]} is not present in the ORGANIZATION_LABELS list. Skipping rename until it is.")
            continue
        try:
            label = repo_labels[name[0]]
        except:
            continue
        label.edit(name=name[1], description=label.description, color=label.color)
        
    # Re-fetch the renamed labels.
    repo_labels = repo_labels = {l.name: l for l in repo.get_labels()}
    repo_label_names = {l for l in repo_labels.keys()}

    # Construct sets of label names to use in processing.
    labels_to_add = organization_label_names - repo_label_names
    labels_to_delete = repo_label_names - organization_label_names
    common_labels = repo_label_names & organization_label_names
    
    # Add new labels, and delete unused ones.
    print(f"{repo.name}: +{labels_to_add}; -{labels_to_delete}")
    for name in labels_to_add:
        original = ORGANIZATION_LABELS[name]
        repo.create_label(name=original[name], color=original[color], description=original[description])
    for name in labels_to_delete:
        repo_labels[name].delete()

    # Ensure common labels share the same colors and descriptions.
    for name in common_labels:
        description = repo_labels[name].description != ORGANIZATION_LABELS[name][description]
        color = repo_labels[name].color != ORGANIZATION_LABELS[name][description]

        if color or description:
            repo_labels[name].edit(ORGANIZATION_LABELS[name][name], ORGANIZATION_LABELS[name][color], ORGANIZATION_LABELS[name][description])
